### ISSUE TITLE
Commits clairs mais titres trop longs

### ISSUE THREAD

**Issue by tanguy-perennou** [simonbeguin/awng-tutorial-simon-beguin#1]
Le texte ajouté à un commit se décompose en 2 parties : 

- un titre, qui doit rester court et synthétique
- un développement, où des détails peuvent être ajoutés sur plusieurs paragraphes

La commande `git commit -m "..."` permet juste d'indiquer le titre, pas le développement. Pour rédiger le développement, il faut passer par la commande `git commit`, qui ouvre un éditeur de texte, souvent `vim`, où le commentaire doit être rédigé sous la forme suivante :

     titre (une ligne, moins de 50 caractères)
     (ligne vide)
     description (plusieurs lignes)

**Comment by tanguy-perennou** [comment]
Pour les **prochains** commits, concentre-toi sur le titre passé à `git commit -m"..."`, ou bien utilise l'éditeur ouvert par `git commit` sans l'option `-m`.

**Comment by simonbeguin** [comment]
D'accord merci je ferais cela pour les prochains !

**Comment by tanguy-perennou** [comment]
👍
